/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmPackage;

import bankPackage.Bank;
import javax.swing.BorderFactory;

/**
 *
 * @author Admin
 */
public class ATMMachine extends javax.swing.JFrame {

    
    private CashMachine cashMachine = new CashMachine(new Bank());
   
    /**
     * Creates new form NewJFrame
     */
    public ATMMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        generalTextArea3 = new javax.swing.JTextField();
        enterAmountTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        enterButton5 = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        pinNumberTextField = new javax.swing.JTextField();
        enterAmountTextArea = new javax.swing.JTextField();
        pinNumberTextArea = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        displayBalanceTextArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        displayEmailTextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        displayIDTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        displayNameTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayAccountTypeTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();

        generalTextArea3.setEditable(false);
        generalTextArea3.setBackground(new java.awt.Color(0, 102, 102));
        generalTextArea3.setFont(new java.awt.Font("Futura Hv BT", 0, 12)); // NOI18N
        generalTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        generalTextArea3.setText("ENTER PIN:");
        generalTextArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalTextArea3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(generalTextArea3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterAmountTextField.setBackground(new java.awt.Color(0, 102, 102));
        enterAmountTextField.setFont(new java.awt.Font("Futura Hv BT", 0, 24)); // NOI18N
        enterAmountTextField.setForeground(new java.awt.Color(255, 255, 255));
        enterAmountTextField.setBorder(null);
        enterAmountTextField.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        getContentPane().add(enterAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 230, 40));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositButton.setFont(new java.awt.Font("Futura Hv BT", 0, 8)); // NOI18N
        depositButton.setText("DEPOSIT");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        jPanel7.add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 50));

        withdrawButton.setFont(new java.awt.Font("Futura Hv BT", 0, 8)); // NOI18N
        withdrawButton.setText("WITHDRAW");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        jPanel7.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 100, 460));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 460));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 40, 460));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(jPanel4);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 460));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 900, 250));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonOne.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 70, 50));

        buttonTwo.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, 50));

        buttonThree.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonThree.setText("3");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });
        jPanel1.add(buttonThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 70, 50));

        buttonFour.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, 40));

        buttonFive.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, 40));

        buttonSix.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 70, 40));

        buttonSeven.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 70, 40));

        buttonEight.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 40));

        buttonNine.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonNine.setText("9");
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });
        jPanel1.add(buttonNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 70, 40));

        buttonZero.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        buttonZero.setText("0");
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });
        jPanel1.add(buttonZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, 30));

        enterButton5.setFont(new java.awt.Font("Futura Hv BT", 0, 14)); // NOI18N
        enterButton5.setText("CLEAR");
        enterButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(enterButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 100, 30));

        enterButton.setFont(new java.awt.Font("Futura Hv BT", 0, 14)); // NOI18N
        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, 30));

        cancelButton.setFont(new java.awt.Font("Futura Hv BT", 0, 14)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 900, 230));

        pinNumberTextField.setBackground(new java.awt.Color(0, 102, 102));
        pinNumberTextField.setFont(new java.awt.Font("Futura Hv BT", 0, 24)); // NOI18N
        pinNumberTextField.setForeground(new java.awt.Color(255, 255, 255));
        pinNumberTextField.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        getContentPane().add(pinNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 120, 40));

        enterAmountTextArea.setEditable(false);
        enterAmountTextArea.setBackground(new java.awt.Color(0, 102, 102));
        enterAmountTextArea.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        enterAmountTextArea.setForeground(new java.awt.Color(255, 255, 255));
        enterAmountTextArea.setBorder(null);
        enterAmountTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterAmountTextAreaActionPerformed(evt);
            }
        });
        getContentPane().add(enterAmountTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 230, 40));

        pinNumberTextArea.setEditable(false);
        pinNumberTextArea.setBackground(new java.awt.Color(0, 102, 102));
        pinNumberTextArea.setFont(new java.awt.Font("Futura Hv BT", 0, 18)); // NOI18N
        pinNumberTextArea.setForeground(new java.awt.Color(255, 255, 255));
        pinNumberTextArea.setText("ENTER PIN:");
        pinNumberTextArea.setBorder(null);
        pinNumberTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinNumberTextAreaActionPerformed(evt);
            }
        });
        getContentPane().add(pinNumberTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 120, 60));

        jScrollPane9.setBorder(null);

        displayBalanceTextArea.setEditable(false);
        displayBalanceTextArea.setBackground(new java.awt.Color(0, 102, 102));
        displayBalanceTextArea.setColumns(20);
        displayBalanceTextArea.setForeground(new java.awt.Color(255, 255, 255));
        displayBalanceTextArea.setRows(1);
        displayBalanceTextArea.setBorder(null);
        jScrollPane9.setViewportView(displayBalanceTextArea);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 350, 30));

        jScrollPane8.setBorder(null);

        displayEmailTextArea.setEditable(false);
        displayEmailTextArea.setBackground(new java.awt.Color(0, 102, 102));
        displayEmailTextArea.setColumns(20);
        displayEmailTextArea.setForeground(new java.awt.Color(255, 255, 255));
        displayEmailTextArea.setRows(1);
        displayEmailTextArea.setBorder(null);
        jScrollPane8.setViewportView(displayEmailTextArea);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 350, 30));

        jScrollPane7.setBorder(null);

        displayIDTextArea.setEditable(false);
        displayIDTextArea.setBackground(new java.awt.Color(0, 102, 102));
        displayIDTextArea.setColumns(20);
        displayIDTextArea.setForeground(new java.awt.Color(255, 255, 255));
        displayIDTextArea.setRows(1);
        displayIDTextArea.setBorder(null);
        jScrollPane7.setViewportView(displayIDTextArea);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 350, 30));

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        displayNameTextArea.setEditable(false);
        displayNameTextArea.setBackground(new java.awt.Color(0, 102, 102));
        displayNameTextArea.setColumns(10);
        displayNameTextArea.setForeground(new java.awt.Color(255, 255, 255));
        displayNameTextArea.setRows(1);
        displayNameTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 0, true));
        displayNameTextArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(displayNameTextArea);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 350, 30));

        jScrollPane1.setBorder(null);

        displayAccountTypeTextArea.setEditable(false);
        displayAccountTypeTextArea.setBackground(new java.awt.Color(0, 102, 102));
        displayAccountTypeTextArea.setColumns(20);
        displayAccountTypeTextArea.setForeground(new java.awt.Color(255, 255, 255));
        displayAccountTypeTextArea.setRows(1);
        displayAccountTypeTextArea.setBorder(null);
        jScrollPane1.setViewportView(displayAccountTypeTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 350, 30));

        jScrollPane2.setBorder(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 370, 330));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.add(jPanel11);

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 370, 40));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jPanel12.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 50));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 370, 90));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 240, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
            int pin = Integer.parseInt(pinNumberTextField.getText());

            
            if(cashMachine.login(pin) == true) {
        
                pinNumberTextField.setText("");
                pinNumberTextArea.setText("");
                pinNumberTextField.setEditable(false);
                pinNumberTextField.setBorder(null);
                
                enterAmountTextArea.setEnabled(true);
                enterAmountTextField.setEnabled(true);
                enterAmountTextArea.setText("Enter Amount:");
                enterAmountTextField.setText("");
                
                
                depositButton.setEnabled(true);
                withdrawButton.setEnabled(true);
                enterAmountTextField.setEditable(true); 
                displayNameTextArea.setText(cashMachine.getNameString());
                displayIDTextArea.setText(cashMachine.getIDString());
                displayEmailTextArea.setText(cashMachine.getEmailString());
                displayBalanceTextArea.setText(cashMachine.getBalanceString());
                
    
            } else {
                displayNameTextArea.setText("No data found!");
            }
            
            

            
            
            
    }//GEN-LAST:event_enterButtonActionPerformed

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
         enterAmountTextField.setText(enterAmountTextField.getText()+"0");
    }//GEN-LAST:event_buttonZeroActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
      
       int amount = Integer.parseInt(enterAmountTextField.getText());
       

          cashMachine.deposit(amount);
          displayBalanceTextArea.setText(cashMachine.getBalanceString());
       
        
        

    }//GEN-LAST:event_depositButtonActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"9");
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"7");
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"8");
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"5");
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"4");
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"2");
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"6");
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"3");
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        enterAmountTextField.setText(enterAmountTextField.getText()+"1");
    }//GEN-LAST:event_buttonOneActionPerformed

    private void enterButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterButton5ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
                enterAmountTextArea.setText("");
                enterAmountTextField.setText("");
                enterAmountTextField.setEditable(false);
                
                
                pinNumberTextArea.setText("Enter Pin:");
                pinNumberTextField.setBorder(BorderFactory.createEmptyBorder(0,10,10,10));
                pinNumberTextField.setEditable(true);
                
                
                
                

                depositButton.setEnabled(false);
                withdrawButton.setEnabled(false);
                enterAmountTextField.setEditable(true); 
                enterAmountTextField.setText(""); 
                displayNameTextArea.setText("");
                displayIDTextArea.setText("");
                displayEmailTextArea.setText("");
                displayBalanceTextArea.setText("");
                
                
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void pinNumberTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinNumberTextAreaActionPerformed

    }//GEN-LAST:event_pinNumberTextAreaActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
         int amount = Integer.parseInt(enterAmountTextField.getText());
            cashMachine.withdraw(amount);

            displayBalanceTextArea.setText(cashMachine.getBalanceString());

    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void enterAmountTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterAmountTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterAmountTextAreaActionPerformed

    private void generalTextArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalTextArea3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalTextArea3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMMachine().setVisible(true);
                depositButton.setEnabled(false);
                withdrawButton.setEnabled(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JButton cancelButton;
    private static javax.swing.JButton depositButton;
    private javax.swing.JTextArea displayAccountTypeTextArea;
    private javax.swing.JTextArea displayBalanceTextArea;
    private javax.swing.JTextArea displayEmailTextArea;
    private javax.swing.JTextArea displayIDTextArea;
    private javax.swing.JTextArea displayNameTextArea;
    private javax.swing.JTextField enterAmountTextArea;
    private javax.swing.JTextField enterAmountTextField;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton enterButton5;
    private javax.swing.JTextField generalTextArea3;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField pinNumberTextArea;
    private javax.swing.JTextField pinNumberTextField;
    private static javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
}
